Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Controllers/RecSearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SearchClientWebApp;
using SearchClientWebApp.Models;

namespace SearchClientWebApp.Areas.SME.Models
{
    public class RecSearchController : Controller
    {
        private mifosEntitiesConnection db = new mifosEntitiesConnection();

        // GET: customers
        public ActionResult Index(string SearchStr, int pageNumber = 0)

        {
            int[] myInts = {453,454,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,555,556,598,605,619,635,636};
            ViewBag.SearchStr = SearchStr;
            ViewBag.PageNumber = pageNumber;
            const int pageSize = 25;
            List<CustomerBrefRec.GroupSummaryModel> customers = new List<CustomerBrefRec.GroupSummaryModel>();
            if (!String.IsNullOrEmpty(SearchStr))
            {
                customers = db.customers.Select(p => new CustomerBrefRec.GroupSummaryModel
                {
                    CUSTOMER_ID = p.CUSTOMER_ID,
                    GLOBAL_CUST_NUM = p.GLOBAL_CUST_NUM,
                    DISPLAY_NAME = p.DISPLAY_NAME,
                    //DISPLAY_ADDRESS = p.DISPLAY_ADDRESS,
                    GOVERNMENT_ID = p.GOVERNMENT_ID,

                    //customer_address_detail = p.customer_address_detail,
                    office = p.office,
                    pers = p.personnel,
                     name = p.FIRST_NAME,
                    last = p.LAST_NAME
                    
                })

                      .OrderBy(p => p.DISPLAY_NAME).Skip(pageSize * pageNumber)
                .Take(pageSize)
                .Where(d => (d.DISPLAY_NAME.Equals(SearchStr) || (d.name + " " + d.last).Equals(SearchStr) || d.GOVERNMENT_ID.Contains(SearchStr))
                             /*  || s.GLOBAL_CUST_NUM.Contains(SearchStr)*/ && 
                               (myInts).Contains(d.pers.PERSONNEL_ID) 
                               ) .ToList();


                return View(customers.ToList());
            }
            else
            {
                return View(customers);
            }
        }

        // GET: customers/Details/5
        public ActionResult Details(int? id)
        {
            CustomerDetail.SummaryModel customerModel = new CustomerDetail.SummaryModel();
            customer customer = new customer();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            customer = db.customers.Find(id);

            customerModel.DISPLAY_NAME = customer.DISPLAY_NAME;
            customerModel.customer_state = customer.customer_state;
            customerModel.customer_detail = customer.customer_detail;
            customerModel.CUSTOMER_ID = customer.CUSTOMER_ID;
            customerModel.GLOBAL_CUST_NUM = customer.GLOBAL_CUST_NUM;
            customerModel.office = customer.office;
            customerModel.personnel = customer.personnel;
            customerModel.GOVERNMENT_ID = customer.GOVERNMENT_ID;
            customerModel.DATE_OF_BIRTH = customer.DATE_OF_BIRTH;
            customerModel.DISCRIMINATOR = customer.DISCRIMINATOR;
            customerModel.OldMIS = customer.EXTERNAL_ID;
            customerModel.Address = customer.DISPLAY_ADDRESS;

            if (customerModel == null)
            {
                return HttpNotFound();
            }
            return View(customerModel);
        }

 



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Controllers/RecoveryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SearchClientWebApp;
using System.Web.Script.Services;
using System.Web.Services;
using SearchClientWebApp.Areas.SME.Models;

namespace SearchClientWebApp.Areas.SME.Controllers
{
    public class RecoveryController : Controller
    {
        private mifosEntitiesConnection db = new mifosEntitiesConnection();

        // GET: Recovery
        public async Task<ActionResult> Index()
        {
            var rec_collection = db.rec_collection.Include(r => r.account).Include(r => r.rec_lookupvalue).Include(r => r.rec_lookupvalue1).Include(r => r.rec_lookupvalue2).Select(p => new CustomRec
            {

                Account_id = p.Account_id,
                CollOrLegal = p.CollOrLegal,
                Type = p.Type,
                DateOfTransfer = p.DateOfTransfer,
                amount = p.amount,
                TypeFollowup = p.TypeFollowup,
                rec_lookupvalue = p.rec_lookupvalue,
                rec_lookupvalue1 = p.rec_lookupvalue1,
                rec_lookupvalue2 = p.rec_lookupvalue2,
              
                
            });
            
            return View(await rec_collection.ToListAsync());
        }

        // GET: Recovery/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            return View(rec_collection);
        }

        // GET: Recovery/Create
        [WebMethod]
        [ScriptMethod(UseHttpGet = true)]
        public ActionResult FillCity(int state)
        {
            IQueryable<State> cities;
            if (state == 9)
            {
                 cities = db.rec_lookupvalue.Where(p => p.EntityId == 1).ToList().Select(item => new State
                 {
                     ID = item.LookupValueId,
                     StateName = item.lookupValueName
                 }).AsQueryable(); 
                return Json(cities, JsonRequestBehavior.AllowGet);
            }
           cities = db.rec_lookupvalue.Where(p => p.EntityId == 3).ToList().Select(item => new State
            {
                ID = item.LookupValueId,
                StateName = item.lookupValueName
            }).AsQueryable(); ;
                  return Json(cities, JsonRequestBehavior.AllowGet);
        }


        
        public ActionResult FillCity2(int state)
        {
            IQueryable<State> cities;
            if (state == 9)
            {
                cities = db.rec_lookupvalue.Where(p => p.EntityId == 2).ToList().Select(item => new State
                {
                    ID = item.LookupValueId,
                    StateName = item.lookupValueName
                }).AsQueryable();
                return Json(cities, JsonRequestBehavior.AllowGet);
            }
            cities = db.rec_lookupvalue.Where(p => p.EntityId == 4).ToList().Select(item => new State
            {
                ID = item.LookupValueId,
                StateName = item.lookupValueName
            }).AsQueryable(); ;
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(int? id)
        {
            ViewBag.Account_id = id;
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 5), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 2), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup1 = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 4), "LookupValueId", "lookupValueName");
            //ViewBag.Type = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 1), "LookupValueId", "lookupValueName");
            //ViewBag.Type1 = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 3), "LookupValueId", "lookupValueName");

            return View();
        }

        // POST: Recovery/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int? id, [Bind(Include = "Account_id,CollOrLegal,Type,DateOfTransfer,amount,TypeFollowup")] rec_collection rec_collection)
        {
            if (ModelState.IsValid)
            {
                db.rec_collection.Add(rec_collection);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Account_id = id;
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 5), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 2), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup1 = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 4), "LookupValueId", "lookupValueName");
            //ViewBag.Type = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 1), "LookupValueId", "lookupValueName");
            //ViewBag.Type1 = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 3), "LookupValueId", "lookupValueName");
            return View(rec_collection);
        }

        // GET: Recovery/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            ViewBag.Account_id = new SelectList(db.accounts, "ACCOUNT_ID", "GLOBAL_ACCOUNT_NUM", rec_collection.Account_id);
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.CollOrLegal);
            ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.TypeFollowup);
            ViewBag.Type = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.Type);
            return View(rec_collection);
        }

        // POST: Recovery/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Account_id,CollOrLegal,Type,DateOfTransfer,amount,TypeFollowup")] rec_collection rec_collection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rec_collection).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Account_id = new SelectList(db.accounts, "ACCOUNT_ID", "GLOBAL_ACCOUNT_NUM", rec_collection.Account_id);
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.CollOrLegal);
            ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.TypeFollowup);
            ViewBag.Type = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.Type);
            return View(rec_collection);
        }

        // GET: Recovery/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            return View(rec_collection);
        }

        // POST: Recovery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            db.rec_collection.Remove(rec_collection);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Views/Recovery/Create.cshtml
@model SearchClientWebApp.rec_collection

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>rec_collection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Account_id, "Account_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account_id, new { htmlAttributes = new { @class = "form-control", @Value =ViewBag.account_id, @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.Account_id, "", new { @class = "text-danger" })
            
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollOrLegal, "CollOrLegal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CollOrLegal", null, htmlAttributes: new { @class = "form-control", @id = "BindOther", @onchange = "FillCity()" })
                @Html.ValidationMessageFor(model => model.CollOrLegal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList(Enumerable.Empty<SelectListItem>(), "ID", "StateName"),"Select city",new { @class = "form-control",  @id = "bindType" }) 
                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfTransfer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfTransfer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfTransfer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeFollowup, "TypeFollowup", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeFollowup, new SelectList(Enumerable.Empty<SelectListItem>(), "ID", "StateName"), "Select city", new { @class = "form-control", @id = "bindType2" })
                @Html.ValidationMessageFor(model => model.TypeFollowup, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>

    
  function FillCity() {
      var stateId = $('#BindOther').val();
    $.ajax({
        url: '/Recovery/FillCity',
        type: "GET",
        dataType: "JSON",
        data: { state: stateId },
        success: function (cities) {
            $("#bindType").html(""); // clear before appending new list
            $.each(cities, function (i, city) {
                $("#bindType").append(
                    $('<option></option>').val(city.ID).html(city.StateName));
            });
        }
    });
    $.ajax({
        url: '/Recovery/FillCity2',
        type: "GET",
        dataType: "JSON",
        data: { state: stateId },
        success: function (cities) {
            $("#bindType2").html(""); // clear before appending new list
            $.each(cities, function (i, city) {
                $("#bindType2").append(
                    $('<option></option>').val(city.ID).html(city.StateName));
            });
        }
    });
  }
</script>

    <script>
        $(document).ready(function () { FillCity() });
    </script>


  
}

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Views/Recovery/Delete.cshtml
@model SearchClientWebApp.rec_collection

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>rec_collection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateOfTransfer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfTransfer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.account.GLOBAL_ACCOUNT_NUM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.account.GLOBAL_ACCOUNT_NUM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue.lookupValueName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue1.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue1.lookupValueName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue2.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue2.lookupValueName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Views/Recovery/Details.cshtml
@model SearchClientWebApp.rec_collection

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>rec_collection</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateOfTransfer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfTransfer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.account.GLOBAL_ACCOUNT_NUM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.account.GLOBAL_ACCOUNT_NUM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue.lookupValueName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue1.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue1.lookupValueName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rec_lookupvalue2.lookupValueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rec_lookupvalue2.lookupValueName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Account_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Views/Recovery/Edit.cshtml
@model SearchClientWebApp.rec_collection

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>rec_collection</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Account_id)

        <div class="form-group">
            @Html.LabelFor(model => model.CollOrLegal, "CollOrLegal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CollOrLegal", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CollOrLegal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfTransfer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfTransfer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfTransfer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeFollowup, "TypeFollowup", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeFollowup", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeFollowup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Views/Recovery/Index.cshtml
@model IEnumerable<SearchClientWebApp.Areas.SME.Models.CustomRec>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    @Html.ActionLink("Create New", "Index","RecSearch")
</p>
<h2>Active Recovery</h2>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            CustomerID
        </th>
        <th>
            Date
        </th>
       
        <th>
            AccountID
        </th>
        <th>
            CollOrLegal
        </th>
        <th>
            Type
        </th>
        <th>
            TypeFollowup
        </th>
        <th>
            Amount
        </th>
        <th>
            totalpaid
        </th>
        <th>
            Due
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.detail.displayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.detail.customerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfTransfer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Account_id)
        </td>
                
        <td>
            @Html.DisplayFor(modelItem => item.rec_lookupvalue.lookupValueName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rec_lookupvalue1.lookupValueName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rec_lookupvalue2.lookupValueName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.totalpaid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Due)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Account_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Account_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Account_id })
            @Html.ActionLink("AddRepayment", "create","Payment", new { id = item.Account_id },null)


        </td>
    </tr>
}

</table>