Projects/SearchClientWebApp/SearchClientWebApp/Areas/OP/Controllers/DataTableController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SearchClientWebApp;
using SearchClientWebApp.Models;
using System.Web.Services;
using System.Web.Script.Services;
using System.Threading;

namespace SearchClientWebApp.Areas.OP.Models
{
    public class DataTableController : Controller
    {
        private mifosEntitiesConnection db = new mifosEntitiesConnection();

        // GET: customers
        public async Task<ActionResult> Index(string SearchStr, int pageNumber = 0)
        {
            ViewBag.SearchStr = SearchStr;

            ViewBag.PageNumber = pageNumber;
            const int pageSize = 25;
            List<CustomerBref.GroupSummaryModel> customers = new List<CustomerBref.GroupSummaryModel>();
            if (!String.IsNullOrEmpty(SearchStr))
            {
                List<string> splited = new List<string>(SearchStr.Split(' '));
                customers = await db.customers.Select(p => new CustomerBref.GroupSummaryModel
                {
                    CUSTOMER_ID = p.CUSTOMER_ID,
                    GLOBAL_CUST_NUM = p.GLOBAL_CUST_NUM,
                    DISPLAY_NAME = p.DISPLAY_NAME,
                    GOVERNMENT_ID = p.GOVERNMENT_ID,
                    office = p.office,
                    name = p.FIRST_NAME,                   
                    last = p.LAST_NAME



                })

                      .OrderBy(p => p.DISPLAY_NAME).Skip(pageSize * pageNumber)
                .Take(pageSize).Where(d => d.DISPLAY_NAME.Equals(SearchStr) || (d.name + " " + d.last).Equals(SearchStr) || d.GOVERNMENT_ID.Contains(SearchStr)).ToListAsync();

                //.Where(p => splited.All(r => (r.Contains(p.name)) || (r.Contains(p.middle) ) || (r.Contains(p.last))))
                //               .ToList();


                return View(customers);
            }
            else
            {
                return View(customers);
            }
        }

        // GET: customers/Details/5
        public ActionResult Details(int? id)
        {
            CustomerDetail.SummaryModel customerModel = new CustomerDetail.SummaryModel();
            customer customer = new customer();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            customer = db.customers.Find(id);

            customerModel.DISPLAY_NAME = customer.DISPLAY_NAME;
            customerModel.customer_state = customer.customer_state;
            customerModel.customer_detail = customer.customer_detail;
            customerModel.CUSTOMER_ID = customer.CUSTOMER_ID;
            customerModel.GLOBAL_CUST_NUM = customer.GLOBAL_CUST_NUM;
            customerModel.office = customer.office;
            customerModel.personnel = customer.personnel;
            customerModel.GOVERNMENT_ID = customer.GOVERNMENT_ID;
            customerModel.DATE_OF_BIRTH = customer.DATE_OF_BIRTH;
            customerModel.DISCRIMINATOR = customer.DISCRIMINATOR;
            customerModel.OldMIS = customer.EXTERNAL_ID;
            customerModel.Address = customer.DISPLAY_ADDRESS;

            if (customerModel == null)
            {
                return HttpNotFound();
            }
            return View(customerModel);
        }

        [HttpPost]
        public ActionResult Search(string term)
        {
            Suggname sugg = new Suggname();
            return Json(sugg.search(term), JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projects/SearchClientWebApp/SearchClientWebApp/Areas/SME/Controllers/RecoveryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SearchClientWebApp;
using System.Web.Script.Services;
using System.Web.Services;
using SearchClientWebApp.Areas.SME.Models;

namespace SearchClientWebApp.Areas.SME.Controllers
{
    public class RecoveryController : Controller
    {
        private mifosEntitiesConnection db = new mifosEntitiesConnection();

        // GET: Recovery
        public async Task<ActionResult> Index()
        {
            var rec_collection = db.rec_collection.Include(r => r.account).Include(r => r.rec_lookupvalue).Include(r => r.rec_lookupvalue1).Include(r => r.rec_lookupvalue2).Select(p => new CustomRec
            {

                Account_id = p.Account_id,
                CollOrLegal = p.CollOrLegal,
                Type = p.Type,
                DateOfTransfer = p.DateOfTransfer,
                amount = p.amount,
                TypeFollowup = p.TypeFollowup,
                rec_lookupvalue = p.rec_lookupvalue,
                rec_lookupvalue1 = p.rec_lookupvalue1,
                rec_lookupvalue2 = p.rec_lookupvalue2,
              
                
            });
            
            return View(await rec_collection.ToListAsync());
        }

        // GET: Recovery/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            return View(rec_collection);
        }

        // GET: Recovery/Create
        [WebMethod]
        [ScriptMethod(UseHttpGet = true)]
        public ActionResult FillCity(int state)
        {
            IQueryable<State> cities;
            if (state == 9)
            {
                 cities = db.rec_lookupvalue.Where(p => p.EntityId == 1).ToList().Select(item => new State
                 {
                     ID = item.LookupValueId,
                     StateName = item.lookupValueName
                 }).AsQueryable(); 
                return Json(cities, JsonRequestBehavior.AllowGet);
            }
           cities = db.rec_lookupvalue.Where(p => p.EntityId == 3).ToList().Select(item => new State
            {
                ID = item.LookupValueId,
                StateName = item.lookupValueName
            }).AsQueryable(); ;
                  return Json(cities, JsonRequestBehavior.AllowGet);
        }


        
        public ActionResult FillCity2(int state)
        {
            IQueryable<State> cities;
            if (state == 9)
            {
                cities = db.rec_lookupvalue.Where(p => p.EntityId == 2).ToList().Select(item => new State
                {
                    ID = item.LookupValueId,
                    StateName = item.lookupValueName
                }).AsQueryable();
                return Json(cities, JsonRequestBehavior.AllowGet);
            }
            cities = db.rec_lookupvalue.Where(p => p.EntityId == 4).ToList().Select(item => new State
            {
                ID = item.LookupValueId,
                StateName = item.lookupValueName
            }).AsQueryable(); ;
            return Json(cities, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(int? id)
        {
            ViewBag.Account_id = id;
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 5), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 2), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup1 = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 4), "LookupValueId", "lookupValueName");
            //ViewBag.Type = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 1), "LookupValueId", "lookupValueName");
            //ViewBag.Type1 = new SelectList(db.rec_lookupvalue.Where(p => p.EntityId == 3), "LookupValueId", "lookupValueName");

            return View();
        }

        // POST: Recovery/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(int? id, [Bind(Include = "Account_id,CollOrLegal,Type,DateOfTransfer,amount,TypeFollowup")] rec_collection rec_collection)
        {
            if (ModelState.IsValid)
            {
                db.rec_collection.Add(rec_collection);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Account_id = id;
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 5), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 2), "LookupValueId", "lookupValueName");
            //ViewBag.TypeFollowup1 = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 4), "LookupValueId", "lookupValueName");
            //ViewBag.Type = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 1), "LookupValueId", "lookupValueName");
            //ViewBag.Type1 = new SelectList(db.rec_lookupvalue.Where(p => p.LookupValueId == 3), "LookupValueId", "lookupValueName");
            return View(rec_collection);
        }

        // GET: Recovery/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            ViewBag.Account_id = new SelectList(db.accounts, "ACCOUNT_ID", "GLOBAL_ACCOUNT_NUM", rec_collection.Account_id);
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.CollOrLegal);
            ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.TypeFollowup);
            ViewBag.Type = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.Type);
            return View(rec_collection);
        }

        // POST: Recovery/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Account_id,CollOrLegal,Type,DateOfTransfer,amount,TypeFollowup")] rec_collection rec_collection)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rec_collection).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Account_id = new SelectList(db.accounts, "ACCOUNT_ID", "GLOBAL_ACCOUNT_NUM", rec_collection.Account_id);
            ViewBag.CollOrLegal = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.CollOrLegal);
            ViewBag.TypeFollowup = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.TypeFollowup);
            ViewBag.Type = new SelectList(db.rec_lookupvalue, "LookupValueId", "lookupValueName", rec_collection.Type);
            return View(rec_collection);
        }

        // GET: Recovery/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            if (rec_collection == null)
            {
                return HttpNotFound();
            }
            return View(rec_collection);
        }

        // POST: Recovery/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            rec_collection rec_collection = await db.rec_collection.FindAsync(id);
            db.rec_collection.Remove(rec_collection);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projects/SearchClientWebApp/SearchClientWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ERP </title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/themes/base/css")
    <link href="~/Content/themes/Custommenu.css" rel="stylesheet" />
</head>
<body>
    <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="./" class="navbar-brand"> Al-Majmoua </a>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                      
                              </li>
                    <li>
                        @Html.ActionLink("Recovery ", "Index", "Recovery", new { area = "SME" }, new { @class = "navbar-brand" })
                    </li>
                    <li>
                        @Html.ActionLink("SearchClient", "Index", "DataTable", new { area = "OP" }, new { @class = "navbar-brand" })
                    </li>
                   
                </ul>
            </nav>
        </div>
        </header>
        @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header" >
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                 
                </div>
                @*<div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>*@
        @*<p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
                    </div>
                </div>
            </div>*@

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - HHERSHY </p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        <script src="~/Scripts/jquery-ui-1.11.4.js"></script>
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.js")
        @Scripts.Render("~/Scripts/DataTables/dataTables.scroller.min.js")


        @RenderSection("scripts", required: false)

</body>
</html>